FROM busybox
# version must match version.jmx-prometheus-javaagent in the parent pom.xml
ARG JMX_EXPORTER_VERSION=0.20.0

ADD target/zv-debezium-connector-postgres-[0-9]*.tar.gz /connectors/
COPY --chmod=0644 --from=lib jmx_prometheus_javaagent-${JMX_EXPORTER_VERSION}.jar /jmx-exporter/jmx_prometheus_javaagent.jar

