#!/usr/bin/env python3
"""Generate deterministic connector parameter YAMLs from the zv-debezium fork.

Parses every ``Field.create(...)`` definition in the main sources of the
postgres source connector and the JDBC sink connector with tree-sitter
(a real Java grammar, no regex heuristics) and writes one YAML file per
connector into ``zv-monitor/analysis``:

    name     - config key (module string constants resolved to literals)
    file     - source file (repo-relative) declaring the Field
    required - true when the definition declares no default
               (or an explicit withRequired), i.e. a value must be supplied
    default  - raw declared default expression (withDefault / withEnum),
               null when none
    type     - ConfigDef.Type declared via withType (withEnum implies STRING),
               falling back to the Field-constructor default STRING
    group    - Field.Group enum name declared via withGroup, falling back to
               the Field-constructor default ADVANCED
    importance - ConfigDef.Importance declared via withImportance, falling
               back to the Field-constructor default MEDIUM

Run from anywhere:  python3 utils/gen_connector_params.py
The output is byte-for-byte deterministic (sorted, no timestamps), and the
generated YAML is round-trip validated with PyYAML before writing.
"""
import sys
from pathlib import Path

try:
    import tree_sitter_java
    import yaml
    from tree_sitter import Language, Parser
except ImportError as exc:  # pragma: no cover - dependency guard
    print(f"error: missing parser package: {exc}", file=sys.stderr)
    print("install with: pip3 install --user --break-system-packages -r utils/requirements.txt",
          file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "zv-monitor" / "analysis"

CONNECTORS = [
    ("zv-debezium/debezium-connector-postgres", "postgres-source",
     "postgres-source-connector-params.yaml"),
    ("zv-debezium/debezium-connector-jdbc", "jdbc-sink",
     "jdbc-sink-connector-params.yaml"),
]

HEADER = """\
# Generated by utils/gen_connector_params.py (runs on every Maven build) - DO NOT EDIT.
# required=true: the Field definition declares no default (and/or withRequired), i.e. a value must be supplied;
# default: raw declared default expression (withDefault / withEnum), null when none.
# type: ConfigDef.Type from withType (withEnum implies STRING);
# group: Field.Group enum name from withGroup; importance: ConfigDef.Importance from withImportance.
# type/group/importance fall back to the io.debezium.config.Field constructor defaults STRING/ADVANCED/MEDIUM.
# Constants are resolved to their in-module string literals; unresolvable tokens stay verbatim.
"""


def yquote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def unescape(literal_text: str) -> str:
    """Strip quotes and unescape a Java string literal."""
    body = literal_text[1:-1]
    out, i = [], 0
    escapes = {"n": "\n", "t": "\t", "r": "\r", '"': '"', "\\": "\\", "'": "'"}
    while i < len(body):
        if body[i] == "\\" and i + 1 < len(body):
            out.append(escapes.get(body[i + 1], body[i + 1]))
            i += 2
        else:
            out.append(body[i])
            i += 1
    return "".join(out)


def collapse(text: str) -> str:
    return " ".join(text.split())


def walk(node):
    """Deterministic pre-order walk of a tree-sitter node tree."""
    stack = [node]
    while stack:
        current = stack.pop()
        yield current
        stack.extend(reversed(current.children))


def collect_constants(root) -> dict:
    """Map CONSTANT_NAME -> string value for `... String CONST = "lit";` fields."""
    consts = {}
    for node in walk(root):
        if node.type != "field_declaration":
            continue
        for child in node.children:
            if child.type != "variable_declarator":
                continue
            name = child.child_by_field_name("name")
            value = child.child_by_field_name("value")
            if name is not None and value is not None and value.type == "string_literal":
                consts.setdefault(name.text.decode(), unescape(value.text.decode()))
    return consts


def expr_to_name(expr, consts) -> str:
    """Resolve a Field.create first argument ("lit" / CONST / Class.CONST / a + b)."""
    if expr is None:
        return ""
    if expr.type == "string_literal":
        return unescape(expr.text.decode())
    if expr.type == "identifier":
        text = expr.text.decode()
        return consts.get(text, text)
    if expr.type == "field_access":
        field = expr.child_by_field_name("field")
        text = field.text.decode() if field is not None else expr.text.decode()
        return consts.get(text, expr.text.decode())
    if expr.type == "binary_expression":
        left = expr_to_name(expr.child_by_field_name("left"), consts)
        right = expr_to_name(expr.child_by_field_name("right"), consts)
        return left + right
    return expr.text.decode()


def argument_nodes(argument_list):
    if argument_list is None:
        return []
    return [c for c in argument_list.children
            if c.type not in (",", "(", ")", "comment")]


def chain_methods(create_node):
    """Climb from the Field.create(...) invocation to the outermost chained call
    and return [(method_name, argument_list_node)] outermost-first."""
    outer = create_node
    while (outer.parent is not None
           and outer.parent.type == "method_invocation"
           and outer.parent.child_by_field_name("object") == outer):
        outer = outer.parent
    methods = []
    node = outer
    while node is not None and node.type == "method_invocation":
        name = node.child_by_field_name("name")
        if name is None:  # not a plain chained method call - stop safely
            break
        methods.append((name.text.decode(), node.child_by_field_name("arguments")))
        node = node.child_by_field_name("object")
    return methods


def qualified_tail(expr) -> str:
    """Reduce a qualified Java token (Type.STRING, ConfigDef.Importance.LOW,
    Field.Group.CONNECTION) to its final enum constant."""
    return expr.text.decode().rsplit(".", 1)[-1]


def group_entry_name(arg) -> str:
    """Extract the Field.Group enum name from a withGroup(...) argument, which
    is normally `Field.createGroupEntry(Field.Group.X[, positionInGroup])`."""
    if arg is None:
        return ""
    if arg.type == "method_invocation":
        name = arg.child_by_field_name("name")
        if name is None or name.text.decode() != "createGroupEntry":
            return ""
        entry_args = argument_nodes(arg.child_by_field_name("arguments"))
        return qualified_tail(entry_args[0]) if entry_args else ""
    return qualified_tail(arg)


def extract_field(create_node, consts, rel_file):
    methods = chain_methods(create_node)
    create_args = argument_nodes(methods[-1][1]) if methods and methods[-1][0] == "create" else []
    name = expr_to_name(create_args[0], consts) if create_args else ""

    default = None
    field_type = None
    group = None
    importance = None
    # methods are outermost-first, i.e. exactly the order in which the
    # with* builder calls are applied at runtime, so later calls win.
    for method_name, args in methods:
        arg_nodes = argument_nodes(args)
        if method_name == "withDefault" and arg_nodes:
            arg = arg_nodes[0]
            if arg.type == "string_literal":
                default = unescape(arg.text.decode())
            elif arg.type == "identifier" and arg.text.decode() in consts:
                default = consts[arg.text.decode()]
            else:
                default = collapse(arg.text.decode())
        elif method_name == "withEnum" and len(arg_nodes) >= 2:
            default = collapse(arg_nodes[1].text.decode())
            field_type = "STRING"  # Field.withEnum applies withType(Type.STRING)
        elif method_name == "withType" and arg_nodes:
            field_type = qualified_tail(arg_nodes[0])
        elif method_name == "withGroup" and arg_nodes:
            group = group_entry_name(arg_nodes[0]) or group
        elif method_name == "withImportance" and arg_nodes:
            importance = qualified_tail(arg_nodes[0])

    required = default is None
    for method_name, args in methods:
        arg_nodes = argument_nodes(args)
        if method_name == "withRequired" and (not arg_nodes or arg_nodes[0].text == b"true"):
            required = True
    # unset type/group/importance fall back to the io.debezium.config.Field
    # constructor defaults (STRING / ADVANCED / MEDIUM).
    return {
        "name": name,
        "file": rel_file,
        "type": field_type or "STRING",
        "group": group or "ADVANCED",
        "importance": importance or "MEDIUM",
        "required": required,
        "default": default,
    }


def parse_module(module_rel: str, label: str, out_path: Path):
    module = ROOT / module_rel
    src_dir = module / "src" / "main" / "java"
    if not src_dir.is_dir():
        sys.exit(f"error: {src_dir} not found")

    parser = Parser(Language(tree_sitter_java.language()))
    java_files = sorted(src_dir.rglob("*.java"))

    # pass 1: string constants across the whole module (first definition wins)
    consts = {}
    trees = []
    for path in java_files:
        tree = parser.parse(path.read_bytes())
        if tree.root_node.has_error:
            print(f"warning: {path} has parse errors", file=sys.stderr)
        trees.append((path, tree))
        for key, value in collect_constants(tree.root_node).items():
            consts.setdefault(key, value)

    # pass 2: Field.create(...) definitions
    rows, seen = [], set()
    for path, tree in trees:
        rel_file = path.relative_to(src_dir).as_posix()
        for node in walk(tree.root_node):
            if node.type != "method_invocation":
                continue
            name_node = node.child_by_field_name("name")
            obj = node.child_by_field_name("object")
            # accept both `Field.create(...)` and fully-qualified
            # `io.debezium.config.Field.create(...)`
            obj_text = obj.text.decode() if obj is not None else None
            if (name_node is not None and name_node.text == b"create"
                    and obj_text is not None
                    and (obj_text == "Field" or obj_text.endswith(".Field"))):
                row = extract_field(node, consts, rel_file)
                key = (row["name"], rel_file)
                if key not in seen:
                    seen.add(key)
                    rows.append(row)

    rows.sort(key=lambda r: (r["name"], r["file"]))

    lines = [HEADER.rstrip("\n"), f"connector: {label}", f"source: {module_rel}",
             f"count: {len(rows)}", "parameters:"]
    for row in rows:
        default = "null" if row["default"] is None else yquote(row["default"])
        lines.append(f"- name: {yquote(row['name'])}")
        lines.append(f"  file: {yquote(row['file'])}")
        lines.append(f"  type: {yquote(row['type'])}")
        lines.append(f"  group: {yquote(row['group'])}")
        lines.append(f"  importance: {yquote(row['importance'])}")
        lines.append(f"  required: {'true' if row['required'] else 'false'}")
        lines.append(f"  default: {default}")
    text = "\n".join(lines) + "\n"

    # round-trip validation: the emitted file must parse back to the same size
    loaded = yaml.safe_load(text)
    if not isinstance(loaded, dict) or len(loaded.get("parameters") or []) != len(rows):
        sys.exit(f"error: generated YAML for {label} failed PyYAML validation")

    out_path.write_text(text, encoding="utf-8")
    print(f"wrote {out_path} ({len(rows)} parameters)", file=sys.stderr)


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for module_rel, label, file_name in CONNECTORS:
        parse_module(module_rel, label, OUT_DIR / file_name)


if __name__ == "__main__":
    main()

